server:
  port: 8849

##Actuator的端点配置，详细了解请点击文上方Actuator连接
#management:
#  endpoints:
#    web:
#      exposure :
#        include: "*"
#      base-path: /minitor/*
#  endpoint:
#    health:
#      show-details: ALWAYS
#  server:
#    port: 8080

# Spring Security Default user name and password

spring:
  redis:
    host: 123.57.130.90
    port: 36379
    password: 123qwe!@#
    # redis client配置，使用lettuce
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0

  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/findfish?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: libbytian123QWE!@#
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 5
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: "SELECT 'x'"
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 10
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    poolPreparedStatements: true
    keepAlive: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    encoding: UTF-8
    basename: message/messages_zh
  level: debug
#  # 定位模板的目录,给返回的页面添加后缀名
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5

# Logger Config
logging:
  level:
    com.vicente.vicentedemo: debug
# mybatis-plus相关配置
mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.libbytian.pan.system.enums
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mybatis/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL

      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'




user:
  agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/7.0.15(0x17000f28) NetType/WIFI Language/zh_CN
  unread:
    weiduyingdan: http://www.unreadmovie.com
  lxxh:
    aidianying: http://520.aiyule.top
  sumsu:
    url: http://520.sumsu.cn/search.php?mod=forum

temp:
  filrooet: 'D:/'
  filePath: /temp

wx:
  mp:
    configs:
      - appId: 11111# 第一个公众号的appid
        secret: 111111# 公众号的appsecret
        token: 1111 # 接口配置里的Token值
        aesKey: 1111 # 接口配置里的EncodingAESKey值
#      - appId: 2222 # 第二个公众号的appid，以下同上
#        secret: 1111
#        token: 111
#        aesKey: 111





